name: Sync to Hugging Face Space
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Create requirements.txt from pyproject.toml
        run: python3 -c 'import tomllib; print("\n".join(tomllib.load(open("pyproject.toml", "rb")).get("project", {}).get("dependencies", [])))' > requirements.txt

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Set up a dummy git identity for the GitHub Action bot
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add requirements.txt
          git commit -m "Auto-generate requirements.txt for Hugging Face"

          git push --force https://ibrahimhabibeg:$HF_TOKEN@huggingface.co/spaces/ibrahimhabibeg/parallel-pagerank HEAD:main
